### ISSUE TITLE
Support for smaller screens

### ISSUE THREAD

**Issue by cmacmackin** [cmacmackin/ford#103]
When I designed the templates for the documentation, I hadn't yet learned about mobile-first web design. As such, while documentation renders nicely on a large screen, it is a complete mess on smaller ones. I should invest some time into using the correct Bootstrap CSS classes to allow for better rendering on, at least, medium size screens.

**Comment by jburgalat** [comment]
It may explain why I did not have the same render on my Macbook compared to my PC. 

I would also suggest that variable description (especially global ones from module) should be set on a separated line. If the description has more than a single line it is not very readable because the related column width is too small.

I have made a quick change to put the description on a separated row on my fork. This may be not the most elegant way to do so but If you are interested I can pull a request.

**Comment by cmacmackin** [comment]
I've redone the HTML templates to be more friendly to small and medium-sized screens. I experimented with putting the description on a second line, but I didn't like how it looked. Unless you're using a really small (phone-sized) screen I find this usually isn't a problem in practice.
