### ISSUE TITLE
ifort preprocessor

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#117]
Suggestion: to have the option to specify that `ifort` should be used for the preprocessing step rather than `gfortran`.

**Comment by cmacmackin** [comment]
I've had it on my to-do list for some time to add the ability to specify which preprocessor command to use. Someone had already requested it--I could have sworn they'd opened an issue for it, but I don't see it on here. It will be in the next release that isn't just bugfixes. However, other than fixing bugs, I'm trying to focus more on my project FIAT at the moment, so that may be a while coming.

**Comment by p-vitt** [comment]
We use [CoCo](http://www.daniellnagle.com/coco.html) as preprocessor. Would be nice to also be able to use that instead of ifort/gfortran.

**Comment by zbeekman** [comment]
If I'm not mistake, I believe Chris mentioned (elsewhere) that the plan is to allow an arbitrary user specified command to be used...

**Comment by cmacmackin** [comment]
Fixed with PR #129 .
