### ISSUE TITLE
Escape characters in string

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#136]
I get a parsing error (`Warning: Error parsing blah.f90. missing group name`, and the documentation file is not generated) with the following file:

````Fortran
!*******************************************************************************
!>
!   blah.

    module blah_module

    character(len=*),parameter,public :: gamma = '\gamma'

    end module blah_module
!*******************************************************************************
````
Seems to be caused by the `\` character in the string.

**Comment by cmacmackin** [comment]
Interesting. This is because I remove all string before parsing the code and then substitute them back in when extracting variable initializations. However, when substituting back in, the regex package thinks the `\g` means a group should be used in the substitution but then can't find a group name. This will be a bit tricky to deal with, but I'll figure something out.

**Comment by cmacmackin** [comment]
Fixed. Will be in the next release (hopefully later today).

**Comment by jacobwilliams** [comment]
Thanks! Greatly appreciated!
