### ISSUE TITLE
exclude_dir not recursive

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#177]
Was wondering if the `exclude_dir` option should be recursive? It doesn't seem to be. For example:

```
exclude_dir: ./src/tests
```

Files in `./src/tests/blah` are still being parsed. 

It's not a big deal for me, since I can workaround this by adding:

```
exclude_dir: ./src/tests
             ./src/tests/blah
```

But I wanted to report it. It seems like if somebody had a complicated directory structure they wanted to exclude it would be tedious to have to put all the subdirectories.

**Comment by szaghi** [comment]
I confirm this behavior.

**Comment by szaghi** [comment]
@cmacmackin 

I add some more info to what reported by @jacobwilliams 

Reading your doc I understand (surely I am wrong) that I can define the paths relatively to the main project file. Let us consider on of my (wrong) FORD main project files

```
project: MORTIF
src_dir: ../src
exclude_dir: ../src/third_party/PENF/src/lib
             ../src/third_party/PENF/src/tests
output_dir: html/publish/
project_github: https://github.com/szaghi/MORTIF
summary: MORTon Indexer (Z-order) Fortran envinronment
author: Stefano Zaghi
github: https://github.com/szaghi
email: stefano.zaghi@gmail.com
md_extensions: markdown.extensions.toc(anchorlink=True)
               markdown.extensions.smarty(smart_quotes=False)
               markdown.extensions.extra
               markdown_checklist.extension
docmark: <
display: public
         protected
         private
source: true
warn: true
graph: true
extra_mods: iso_fortran_env:https://gcc.gnu.org/onlinedocs/gfortran/ISO_005fFORTRAN_005fENV.html

{!README-MORTIF.md!}
```
In this setup file the source file directory (`../src`) is correctly handled (I run FORD on dir up with respect the main project file), but other paths like the excluded directories (e.g. `../src/third_party/PENF/src/lib`) nope. 

My understanding was that if I use *relative* path with respect the main project file all paths should (or at least could) be in the same format, but this is not the case because the excluded directories so specified are not ignored. To obtain the correct exclusion I have to use the path relative to where I run FORD rather to where is the main project file, namely the correct excluded path is `./src/third_party/PENF/src/lib` (with only 1 dot). 

> This different *handling* between the `src_dir` and `exclude_dir` has initially surprised me. Is this your intended behavior or there is some oddity in handling the kind of paths?

Cheers.

**Comment by cmacmackin** [comment]
Merging in #194 didn't quite fix this because of some issues with when I normalised the user-specified paths. I've now fixed that issue and the bug will be corrected in the next release. This will mean that excluded directories are recursive and that they are parsed relative to the location of the project file.

**Comment by zbeekman** [comment]
@cmacmackin is this in the latest release yet? Or is it only in master? I'm still seeing this behavior.

**Comment by cmacmackin** [comment]
Only in master.

**Comment by zbeekman** [comment]
Any ETA for a release?

**Comment by cmacmackin** [comment]
No firm one. I'm hoping to do some work towards it later this evening.

**Comment by zbeekman** [comment]
Sorry one more quick question: Is there any sort of wildcard syntax for file names in meta data?

**Comment by cmacmackin** [comment]
No, not at present.

**Comment by zbeekman** [comment]
Been using python a lot more for work, so I hope to be able to contribute a bit more and fix/improve things as I find them, FYI. Thanks again for such an awesome tool and all your hard work.
