### ISSUE TITLE
Runtime error: markdown

### ISSUE THREAD

**Issue by acroucher** [cmacmackin/ford#26]
hi
I just installed FORD and set up a simple test, but when I run it's crashing with the following error:

No handlers could be found for logger "MARKDOWN"
Traceback (most recent call last):
  File "/usr/local/bin/ford", line 9, in <module>
    load_entry_point('FORD==1.1.0', 'console_scripts', 'ford')()
  File "/usr/local/lib/python2.7/dist-packages/ford/__init__.py", line 65, in main
    extension_configs={'markdown.extensions.codehilite':{'linenums':True}})
  File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 134, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 166, in registerExtensions
    % (ext.__class__.__module__, ext.__class__.__name__))
ValueError: Extension "__builtin__.NoneType" must be of type: "markdown.Extension".

Could this be caused by one of the FORD dependencies being too old? I saw that all of them (apart from markdown-include) were in my package manager (apt on Debian Wheezy), so installed them via apt, then used pip to install markdown-include and finally FORD itself.

Versions of the dependencies are as follows (from pip freeze):
Jinja2==2.6
Pygments==1.5
toposort==1.1
Markdown==2.1.1
beautifulsoup4==4.1.0
markdown-include==0.4.2

Any help appreciated!

Cheers, Adrian

**Comment by acroucher** [comment]
It's OK, it looks like it was an older version of markdown that caused the problem. I uninstalled it from apt and installed using pip, which gives Markdown==2.5.2, and that fixed it.

**Comment by acroucher** [comment]
Maybe pip should complain when installing FORD, if the version of markdown is not recent enough?

**Comment by cmacmackin** [comment]
Sorry for the delayed response. I haven't been well for the last few days, plus I have some work to catch up on. I have found in the past that Markdown can be quite particular about which version you use. I suspect that the cause of the problem here is that I ask the codehilite to provide line-numbering. Presumably this feature was not present in Markdown 2.1.1. I think I'll just remove the use of line-numbering in the next release, as it is not really necessary for the code fragments which codehilite would be dealing with. All the same, I probably should find out what is the earliest version of different packages that I need.

**Comment by acroucher** [comment]
Thanks Chris. Hope you are well again soon!
