### ISSUE TITLE
object bound procedure, abstract interface

### ISSUE THREAD

**Issue by brietzke** [cmacmackin/ford#30]
Hi Chris,

sorry for accidently submitted previous issue - something fell on my keyboard. (it may be deleted of course - if at all possible).
However, today I found the ford tool and I already like it more than other tools with respect to modern fortran. I do some fortran programming as well as fortran teaching at our computation center - and to some extend - tools are also a subject.
I wonder whether it would be relatively easy to have the case of an abtract interface and its usage within an object bound procedure properly implemented (procedure pointer as type component with interface), e.g.:

  type my1_t                                                                                                              
     private
     real :: r !! data                                                                                                                               
     integer :: i !! index                                                                                                                           
     procedure(afunc1),pointer,public :: strategy => null()!! object bound 
  end type my1_t
  abstract interface
     function afunc1(s)result(x)
       import my1_t
       class(my1_t), intent(in) :: s
       real :: x
     end function afunc1
  end interface

currently it seams that in the ford-generated documentation does leave the procedure pointer with out interface: procedure() instead of procedure(afunc1)
also the polymorphic type in the argument list of the abstract interface does not show up properly:
class() instead of class(my1_t).

highly appreciate your work anyway.
thanks
Gilbert

**Comment by cmacmackin** [comment]
Those are definitely both serious problems to be addressed. I'm particularly concerned that polymorphic variable types aren't showing up. It's also strange that the abstract interface isn't even being printed--I was thinking that FORD did do that and the only issue was that it didn't provide a hyperlink. I'll definitely take a look at that. That said, I've decided that any major work on FORD (and a problem this serious likely counts as major) will have to be put off until the end of the semester. I'm busy with class-work and my thesis right now. Hopefully I can get this fixed in April!

**Comment by cmacmackin** [comment]
All fixed. The latest GitHub version should produce the correct output now. I'll be putting a new release out on PyPI shortly.

**Comment by cmacmackin** [comment]
These changes are now available on PyPI
