### ISSUE TITLE
setup.* requires README.rst while everthing else uses README.md

### ISSUE THREAD

**Issue by ebo** [cmacmackin/ford#31]
The links need to be made consistent.  Trivial fix, but it cannot install like it is.

Quick fix is to link README.rst to README.md

**Comment by cmacmackin** [comment]
It installs just fine using pip--I've done it. There is a small bugfix which I haven't pushed to pip, but otherwise it's the same as what you'll find here. The reason I have a .rst file in setup.* is because PyPI only uses RST, whereas I generally prefer to work in Markdown (I don't actually know the RST syntax at all) and that was what I wrote the README in originally. I used a converter script to produce an RST file (which gets sent to PyPI) which wasn't being tracked by Git. Regardless, it's up here now.

**Comment by ebo** [comment]
On Apr 7 2015 10:35 AM, Chris MacMackin wrote:
> It installs just fine using pip--I've done it. There is a small
> bugfix which I haven't pushed to pip, but otherwise it's the same as
> what you'll find here. The reason I have a .rst file in setup.* is
> because PyPI only uses RST, whereas I generally prefer to work in
> Markdown (I don't actually know the RST syntax at all) and that was
> what I wrote the README in originally. I used a converter script to
> produce an RST file (which gets sent to PyPI) which wasn't being
> tracked by Git. Regardless, it's up here now.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/cmacmackin/ford/issues/31#issuecomment-90639009

Thanks.  It was a trivial thing, but I did a straight "python setup.py 
install" because I have had problems with pip not playing nicely between 
the system packages, installs into ~/.local/python*, and anaconda.  
Anyway, thanks for getting right on this.

   EBo --
