### ISSUE TITLE
Procedure page suggestions

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#36]
Great job with FORD! I'm starting to use it in earnest, and will pass along some suggestions as they occur to me.  I was wondering if, on the procedure page (for example [this one](http://jacobwilliams.github.io/bspline-fortran/proc/db2ink.html)), we could have the options to:
 * not include the local variable declarations.  In this case, I just want to show the subroutine arguments, but the user doesn't need to know about the local variables.
 * display the syntax-highlighted source code for the routine here on this page.  Maybe at the bottom of the page? I think that would be very convenient.

**Comment by cmacmackin** [comment]
Thanks for the various suggestions. I'll try to get to them over the next few weeks. Right now I'm working on designing a personal website which is the dominant drain on my spare time, but that shouldn't take too much longer.

The first suggestion you make here shouldn't be too bad and I've been meaning to implement something a bit like this anyway. The second one may be more difficult, although it should still be doable. It would likely take a bit of time to finish though.

**Comment by zbeekman** [comment]
:+1: for these features

**Comment by cmacmackin** [comment]
The first of your feature requests has been implemented and is now available on GitHub. I haven't written the documentation yet (in part because I don't like the Wiki getting too far ahead of the PyPI version), but you can turn off the displaying of all local contents of a procedure by adding the line `display: none` to the meta-data of your documentation. See [here](https://github.com/cmacmackin/ford/wiki/Documentation-Meta-Data) for an example of documentation meta-data.

**Comment by cmacmackin** [comment]
I've implemented the source display feature. It can be used for procedures, derived types, and programs. 
You can turn it on for a particular procedure, type, or program, by specifying `source: true` in the meta-data, or turn it on globally by specifying the same in the meta-data of the project file. I'll be authoring a new PyPI release with these features momentarily.

**Comment by jacobwilliams** [comment]
Great job! I'll try it out shortly!
