### ISSUE TITLE
Procedure argument columns

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#44]
Some suggestions for the procedure pages.  Maybe, for the columns (Type, Intent, etc...) do the following:
 * Strip away the trailing commas (so ```integer``` rather than ```integer,```). It would look cleaner that way I think.
 * For ```Intent```, since the column already says "Intent", maybe just use ```in```, ```out```, etc. (rather than ```intent(in)```, etc.)  Not a big deal, feel free to ignore this one.

**Comment by cmacmackin** [comment]
While there might be some things worth doing to tidy the variable/argument lists up, there is a reason why I did things the way I did. One of the design principles which I used when creating FORD's output was that I wanted the output to be similar to actual Fortran code. As such, the variable attributes are all comma-separated and I use `intent(in)` rather than just `in`.
