### ISSUE TITLE
metadata display in interface routines

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#49]
I was wondering if it was necessary to display the metadata in the module procedures listings for an interface.  See example below. I would say leave it out, since in this case, I think it is the description that is most useful.  I think it would look cleaner without the metadata (my opinion...free free to ignore).

![screen shot 2015-06-30 at 9 45 25 pm](https://cloud.githubusercontent.com/assets/6483379/8446515/59f7d48a-1f71-11e5-9102-0f4302471885.png)

**Comment by zbeekman** [comment]
I’m a bit confused about what data you’re proposing to leave out. Just the Author and Date? I think it’s nice to be able to see the specific procedures that a generic/overloaded procedure resolves to, and the call signature of each. Otherwise it can be difficult to track down which procedure a generic actually resolves to… just my $0.02

**Comment by jacobwilliams** [comment]
Just the metadata (in this case author and date shown above). Definitely keep the specific procedure listings.  And the metadata is visible on the procedure page. I just think it's unnecessary in this context.

**Comment by zbeekman** [comment]
ah yes, I agree that the author and date take up valuable screen Realestate in this context.

**Comment by cmacmackin** [comment]
I think what I'll do is make it so that FORD will only display that metadata if the routine doesn't have a page of its own. At present there is no timeline for that change though.

**Comment by cmacmackin** [comment]
I should say that the reason I'm not giving a timeline for this is because I'm not sure whether it would be appropriate in a minor release. This seems a bit too close to changing behaviour, which should really be left to a major release, and I like to have quite a few changes collected before I do one of those. Thoughts?

**Comment by zbeekman** [comment]
For what it's worth I think you could go either way. The proposed change is not urgent from my perspective nor is it terribly substantial. I am happy with whatever you decide.

**Comment by jacobwilliams** [comment]
No rush.

**Comment by cmacmackin** [comment]
This has now been implemented and will be released soon.
