### ISSUE TITLE
feature request: sorting control

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#50]
Hi Chris,
First off, take your time with this one if you like the ideas, there’s no urgency here.

It would be AMAZING to have the ability to change the sorting order in lists and tables generated by FORD. One implementation could be to have sorting specified as meta data or command line switches to pick between say, alphabetical or source order. An even more powerful feature, however, would be some means of letting the user who is browsing the documentation change the sorting. For example, you could sort by visibility, then type, then name for module variables.

I don’t know much about websites and web development, or the tools upon which FORD is built, but dynamic sorting would be really useful when working with a code. If you’re interested and having trouble visualizing what I mean, I could send you an image and a better description…

**Comment by szaghi** [comment]
:+1:

**Comment by cmacmackin** [comment]
I do get what you mean. It should be fairly easy to make FORD change the sort order when it is producing the documentation. Making it happen dynamically, while obviously useful, would be a lot harder. I suspect that it would require encoding the documentation in JSON and then using javascript to display them. That is not something which I would be comfortable doing, as I don't really know javascript very well and because it would represent a major change to how these things are done at the moment.

**Comment by zbeekman** [comment]
yeah I figured it might be a tall order to dynamically sort… I’m picturing something like the details view in a file manager for an OS. Where you can clicking on one column causes it to sort on that column in ascending order, clicking it again sorts on descending order, clicking the next column will sort on file type etc.  well maybe/when FORD will get so popular that everyone writing Fortran is using it, someone else can come along and help us out with the JS.

**Comment by jacobwilliams** [comment]
I also think having a flag to specify which order to use would be great.

**Comment by zbeekman** [comment]
As a start there's alphabetical vs source. But then one might want to group public entities ahead of private ones. Or group variables by type/class. Just brainstorming/spitballing.

**Comment by cmacmackin** [comment]
Added and will be available in the latest release.
