### ISSUE TITLE
Parameter character array bug

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#71]
Something odd is happening in [this](https://github.com/jacobwilliams/Fortran-Astrodynamics-Toolkit/blob/master/src/ephemeris_module.f90) file.  The code:

```Fortran
    character(len=*),dimension(15),parameter :: list_of_bodies = [ & 
                                                        'mercury                ',&
                                                        'venus                  ',&
                                                        'earth                  ',&
                                                        'mars                   ',&
                                                        'jupiter                ',&
                                                        'saturn                 ',&
                                                        'uranus                 ',&
                                                        'neptune                ',&
                                                        'pluto                  ',&
                                                        'moon                   ',&
                                                        'sun                    ',&
                                                        'solar-system barycenter',&
                                                        'earth-moon barycenter  ',&
                                                        'nutations              ',&
                                                        'librations             ']
```

Is being transformed into the following in the documentation:

<img width="600" alt="screen shot 2015-08-17 at 7 43 32 pm" src="https://cloud.githubusercontent.com/assets/6483379/9319806/475db386-4518-11e5-9266-5ce10c40d28e.png">

**Comment by cmacmackin** [comment]
Fixed. FORD temporarily removes all strings from the code (so that it won't get confused by anything in them which could be mistaken for code) and then replaces them when they are needed. Unfortunately, I had assumed that it would only need to replace one string at a time and the result was that all strings were replaced with the contents of the first one. In any case, I've fixed it (and improved the handling of white-space within strings). A new release should be out tomorrow.
