### ISSUE TITLE
Array on write statement mis-identified as function call

### ISSUE THREAD

**Issue by hornekyle** [cmacmackin/ford#86]
The routine dependency graph generated for this function:

http://hornekyle.github.io/PlPlotLib/proc/setup.html

incorrectly identifies the input argument figSize as a function call.

I checked the latest version on pypi and the error still occurs with that version.

**Comment by pheibarrass** [comment]
I had a similar problem, so I wonder whether https://github.com/pheibarrass/ford/commit/a5799843cb406339d893af6fa5882c27b394b916 solves yours?

**Comment by cmacmackin** [comment]
Sorry about this--I think this was because I convert some of the internal records to be lower-case but not others. Normally whenever I compare them I will compare lower-case versions, but I forgot in this instance. The latest GitHub version fixes this. I've tested it on your code and it seems to work.

**Comment by cmacmackin** [comment]
These fixes are now available on PyPI.
