### ISSUE TITLE
Private type-bound procedures listed as public

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#91]
See [here](http://jacobwilliams.github.io/pikaia/type/pikaia_class.html#boundprocedure-ff). The ``ff`` procedure is private, but is listed as public. The procedure it is pointing to (``func_wrapper``) is correctly listed as private. The same situation is also happening with the others (``newpop``, etc.)

**Comment by cmacmackin** [comment]
Actually, the (2003) standard (page 58) says:
> The default accessibility for the procedure bindings of a type is private if the type definition contains a
_binding-private-stmt_, and public otherwise. The accessibility of a procedure binding may be explicitly
declared by an access-spec; otherwise its accessibility is the default for the type definition in which it is
declared.

A _binding-private-statement needs to be specified immediately after the `contains` statement. The `private` statement for the derived type components does not apply to the type-bound procedures.

**Comment by jacobwilliams** [comment]
Mind = Blown! I had no idea!!
