### ISSUE TITLE
Code metrics: SLOC

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#98]
Hi Chris,
I know SLOC is an oft maligned metric, especially when coming from a code quality perspective (i.e. bigger /= better) but it can be useful to know how large a component is when reading its documentation. I was wondering how hard it would be to extract and list SLOC (source lines of code---don't count lines with whitespace only or comments and whitespace only) for each entity that gets documented (probably not for variables.... but for procedures, programs, modules, derived types, and files) and showing what percentage of the total SLOC for that type of entity each individual one takes up.

If it wouldn't be too hard to implement, please consider this issue a feature request. Thanks so much!

**Comment by cmacmackin** [comment]
A basic count should be pretty easy to do and then it wouldn't be hard to add in some logic to compute percentages, etc. The first thing FORD does when analyzing code is strip out white-space and any comments which aren't documentation. Where things might get a little tricky is in considering things like line continuations or the use of semicolons to have multiple statements on a single lexical line. I don't know how these tend to be treated when measuring SLOC, but FORD automatically merges continued lines and splits lines along semicolons. As this is the first step in code analysis (after running the preprocessor) it would not be practical to change this behaviour.

Assuming that is not an issue, a few more questions come to mind. First of all, should documentation be counted in SLOC? By far the easiest thing to do would be to ignore it, because FORD sometimes rearranges it and adds extra blank lines during the initial processing (this is what allows, for example, people to place documentation either before or after the entity that it is documenting). The other question I would have, is how to handle type-bound procedures? That is to say, should their lines of implementation count towards the line-count of the type they are bound to?

**Comment by zbeekman** [comment]
These are my opinions to answer your questions. However, I think most of them have no "right" answer, and as long as what is done is documented, that is fine.

> I don't know how these tend to be treated when measuring SLOC, but FORD automatically merges continued lines and splits lines along semicolons. As this is the first step in code analysis (after running the preprocessor) it would not be practical to change this behaviour.

Correct me if I am wrong, but this has the practical effect of counting statements and declarations rather than lines, no? (Because `;` separate multiple statements on the same line, and `&` continues a statement across a line break, unless there are some other cases I have yet to consider.) I would say that this is totally fine, if not better that counting lines. If my reasoning is sound, you could just call them statements & declarations, not lines. I think this would be as good if not better than counting SLOC

> First of all, should documentation be counted in SLOC? By far the easiest thing to do would be to ignore it, because FORD sometimes rearranges it and adds extra blank lines during the initial processing (this is what allows, for example, people to place documentation either before or after the entity that it is documenting).

My vote would be to ignore the documentation. I think what we're interested in is the properties of the code/library/program rather than the properties of that, plus the documentation system. Of course maintaining documentation can add complexity, but I think that is often a second order effect to  the logic of the software itself.

> The other question I would have, is how to handle type-bound procedures? That is to say, should their lines of implementation count towards the line-count of the type they are bound to?

This question is the least trivial to answer. I think the easiest thing to do would be to just count from `type` etc. to `end type`. This would be a completely acceptable first hack to me. If FORD is already smart enough to know which procedures are implementing TBPs then you could potentially add a second metric, like lines/statements in type declaration and lines/statements including TBPs. Again, I'm not sure there is really a right answer here, but I guess a derived type with few, but very long and complicated TBPs is probably more cumbersome than a TBP with more shorter ones. So if it is feasible, and only one of the two options is going to be implemented I would vote for including the TBP implementations.

**Comment by cmacmackin** [comment]
Added and will be in the next release.
